<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProvincesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('provinces')->delete();
        
        \DB::table('provinces')->insert(array (
            0 => 
            array (
                'id' => 1,
                'country_code' => 'CA',
                'province_code' => 'AB',
                'province_name' => 'Alberta',
                'is_active' => 1,
                'created_at' => '2022-08-09 21:10:52',
                'modified_at' => '2022-08-09 21:10:52',
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'country_code' => 'CA',
                'province_code' => 'BC',
                'province_name' => 'British Columbia',
                'is_active' => 1,
                'created_at' => '2022-08-09 21:10:52',
                'modified_at' => '2022-08-09 21:10:52',
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'country_code' => 'CA',
                'province_code' => 'MB',
                'province_name' => 'Manitoba',
                'is_active' => 1,
                'created_at' => '2022-08-09 21:10:52',
                'modified_at' => '2022-08-09 21:10:52',
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'country_code' => 'CA',
                'province_code' => 'NB',
                'province_name' => 'New Brunswick',
                'is_active' => 1,
                'created_at' => '2022-08-09 21:10:52',
                'modified_at' => '2022-08-09 21:10:52',
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'country_code' => 'CA',
                'province_code' => 'NL',
                'province_name' => 'Newfoundland and Labrador',
                'is_active' => 1,
                'created_at' => '2022-08-09 21:10:52',
                'modified_at' => '2022-08-09 21:10:52',
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'country_code' => 'CA',
                'province_code' => 'NS',
                'province_name' => 'Nova Scotia',
                'is_active' => 1,
                'created_at' => '2022-08-09 21:10:52',
                'modified_at' => '2022-08-09 21:10:52',
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'country_code' => 'CA',
                'province_code' => 'NT',
                'province_name' => 'Northwest Territories',
                'is_active' => 1,
                'created_at' => '2022-08-09 21:10:52',
                'modified_at' => '2022-08-09 21:10:52',
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'country_code' => 'CA',
                'province_code' => 'NU',
                'province_name' => 'Nunavut',
                'is_active' => 1,
                'created_at' => '2022-08-09 21:10:52',
                'modified_at' => '2022-08-09 21:10:52',
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'country_code' => 'CA',
                'province_code' => 'ON',
                'province_name' => 'Ontario',
                'is_active' => 1,
                'created_at' => '2022-08-09 21:10:52',
                'modified_at' => '2022-08-09 21:10:52',
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'country_code' => 'CA',
                'province_code' => 'PE',
                'province_name' => 'Prince Edward Island',
                'is_active' => 1,
                'created_at' => '2022-08-09 21:10:52',
                'modified_at' => '2022-08-09 21:10:52',
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'country_code' => 'CA',
                'province_code' => 'QC',
                'province_name' => 'Quebec',
                'is_active' => 1,
                'created_at' => '2022-08-09 21:10:52',
                'modified_at' => '2022-08-09 21:10:52',
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'country_code' => 'CA',
                'province_code' => 'SK',
                'province_name' => 'Saskatchewan',
                'is_active' => 1,
                'created_at' => '2022-08-09 21:10:52',
                'modified_at' => '2022-08-09 21:10:52',
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'country_code' => 'CA',
                'province_code' => 'YT',
                'province_name' => 'Yukon',
                'is_active' => 1,
                'created_at' => '2022-08-09 21:10:52',
                'modified_at' => '2022-08-09 21:10:52',
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'country_code' => 'US',
                'province_code' => 'AL',
                'province_name' => 'Alabama',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'country_code' => 'US',
                'province_code' => 'AK',
                'province_name' => 'Alaska',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'country_code' => 'US',
                'province_code' => 'AS',
                'province_name' => 'American Samoa',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'country_code' => 'US',
                'province_code' => 'AZ',
                'province_name' => 'Arizona',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'country_code' => 'US',
                'province_code' => 'AR',
                'province_name' => 'Arkansas',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'country_code' => 'US',
                'province_code' => 'CA',
                'province_name' => 'California',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'country_code' => 'US',
                'province_code' => 'CO',
                'province_name' => 'Colorado',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'country_code' => 'US',
                'province_code' => 'CT',
                'province_name' => 'Connecticut',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'country_code' => 'US',
                'province_code' => 'DE',
                'province_name' => 'Delaware',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'country_code' => 'US',
                'province_code' => 'DC',
                'province_name' => 'District Of Columbia',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'country_code' => 'US',
                'province_code' => 'FM',
                'province_name' => 'Federated States Of Micronesia',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'country_code' => 'US',
                'province_code' => 'FL',
                'province_name' => 'Florida',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'country_code' => 'US',
                'province_code' => 'GA',
                'province_name' => 'Georgia',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'country_code' => 'US',
                'province_code' => 'GU',
                'province_name' => 'Guam',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'country_code' => 'US',
                'province_code' => 'HI',
                'province_name' => 'Hawaii',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'country_code' => 'US',
                'province_code' => 'ID',
                'province_name' => 'Idaho',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'country_code' => 'US',
                'province_code' => 'IL',
                'province_name' => 'Illinois',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'country_code' => 'US',
                'province_code' => 'IN',
                'province_name' => 'Indiana',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'country_code' => 'US',
                'province_code' => 'IA',
                'province_name' => 'Iowa',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'country_code' => 'US',
                'province_code' => 'KS',
                'province_name' => 'Kansas',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'country_code' => 'US',
                'province_code' => 'KY',
                'province_name' => 'Kentucky',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'country_code' => 'US',
                'province_code' => 'LA',
                'province_name' => 'Louisiana',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'country_code' => 'US',
                'province_code' => 'ME',
                'province_name' => 'Maine',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'country_code' => 'US',
                'province_code' => 'MH',
                'province_name' => 'Marshall Islands',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'country_code' => 'US',
                'province_code' => 'MD',
                'province_name' => 'Maryland',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'country_code' => 'US',
                'province_code' => 'MA',
                'province_name' => 'Massachusetts',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'country_code' => 'US',
                'province_code' => 'MI',
                'province_name' => 'Michigan',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'country_code' => 'US',
                'province_code' => 'MN',
                'province_name' => 'Minnesota',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'country_code' => 'US',
                'province_code' => 'MS',
                'province_name' => 'Mississippi',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'country_code' => 'US',
                'province_code' => 'MO',
                'province_name' => 'Missouri',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'country_code' => 'US',
                'province_code' => 'MT',
                'province_name' => 'Montana',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'country_code' => 'US',
                'province_code' => 'NE',
                'province_name' => 'Nebraska',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'country_code' => 'US',
                'province_code' => 'NV',
                'province_name' => 'Nevada',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'country_code' => 'US',
                'province_code' => 'NH',
                'province_name' => 'New Hampshire',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'country_code' => 'US',
                'province_code' => 'NJ',
                'province_name' => 'New Jersey',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'country_code' => 'US',
                'province_code' => 'NM',
                'province_name' => 'New Mexico',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'country_code' => 'US',
                'province_code' => 'NY',
                'province_name' => 'New York',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'country_code' => 'US',
                'province_code' => 'NC',
                'province_name' => 'North Carolina',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'country_code' => 'US',
                'province_code' => 'ND',
                'province_name' => 'North Dakota',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'country_code' => 'US',
                'province_code' => 'MP',
                'province_name' => 'Northern Mariana Islands',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'country_code' => 'US',
                'province_code' => 'OH',
                'province_name' => 'Ohio',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'country_code' => 'US',
                'province_code' => 'OK',
                'province_name' => 'Oklahoma',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'country_code' => 'US',
                'province_code' => 'OR',
                'province_name' => 'Oregon',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'country_code' => 'US',
                'province_code' => 'PW',
                'province_name' => 'Palau',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'country_code' => 'US',
                'province_code' => 'PA',
                'province_name' => 'Pennsylvania',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'country_code' => 'US',
                'province_code' => 'PR',
                'province_name' => 'Puerto Rico',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'country_code' => 'US',
                'province_code' => 'RI',
                'province_name' => 'Rhode Island',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'country_code' => 'US',
                'province_code' => 'SC',
                'province_name' => 'South Carolina',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'country_code' => 'US',
                'province_code' => 'SD',
                'province_name' => 'South Dakota',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'country_code' => 'US',
                'province_code' => 'TN',
                'province_name' => 'Tennessee',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'country_code' => 'US',
                'province_code' => 'TX',
                'province_name' => 'Texas',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'country_code' => 'US',
                'province_code' => 'UT',
                'province_name' => 'Utah',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'country_code' => 'US',
                'province_code' => 'VT',
                'province_name' => 'Vermont',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'country_code' => 'US',
                'province_code' => 'VI',
                'province_name' => 'Virgin Islands',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'country_code' => 'US',
                'province_code' => 'VA',
                'province_name' => 'Virginia',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'country_code' => 'US',
                'province_code' => 'WA',
                'province_name' => 'Washington',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'country_code' => 'US',
                'province_code' => 'WV',
                'province_name' => 'West Virginia',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'country_code' => 'US',
                'province_code' => 'WI',
                'province_name' => 'Wisconsin',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'country_code' => 'US',
                'province_code' => 'WY',
                'province_name' => 'Wyoming',
                'is_active' => 1,
                'created_at' => NULL,
                'modified_at' => NULL,
                'created_by' => NULL,
                'modified_by' => NULL,
            ),
        ));
        
        
    }
}